In [1]:
#pandas is a one of the library ,its use to read the database like excel and number related files , 
#it is used for separating the input and output data set
import pandas as pd

In [2]:
#here weare reading the dataset from the inbuild function of pandas
dataset=pd.read_csv("CKD.csv")

In [3]:
# readed dataset
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
# herewe are changing the catagrical input to numerical input 
# new function
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
# this is a new function for reading the input and output names
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
#finding the count of the purchased and unpurchased count or class count
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [7]:
#then here we are separating the input and output with the variables
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[["classification_yes"]]

In [8]:
#sklearn is also one of the library ,we are going to use the libray in every machine learnin project ,its like a default 
#library for ML
#here we are separating the input and output dataset for training and testing prpose ,we are taking 70% for training and 30% for testing testin
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train
X_test

array([[-0.37141827, -0.5043265 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.8626278 ,  1.03502091,  0.94662707, ..., -1.97350876,
        -0.51229234, -0.43852901],
       [ 1.04773471, -0.5043265 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       ...,
       [-1.35865512, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.43071168, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 1.10943702, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901]])

In [11]:
#module creation with classifier 
from sklearn.model_selection import GridSearchCV 

from sklearn.tree import DecisionTreeClassifier

param_grid = {'criterion':['entropy','gini'],'splitter':['best', 'random'],'max_features':['log2','sqrt']}


grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1,scoring='f1_weighted')


grid.fit(X_train, Y_train)

grid

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_features': ['log2', 'sqrt'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [12]:
print("best parameters{}:".format(grid.best_params_))

best parameters{'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'}:

In [13]:
re=grid.cv_results_

In [14]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007396,0.000800,0.023388,0.003929,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.964286,0.894269,0.982051,0.963247,0.957215,0.032529,4
1,0.005796,0.000982,0.017589,0.001020,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.982051,0.929144,0.929513,0.963912,0.957368,0.023842,3
2,0.005594,0.000798,0.018990,0.001789,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.947015,0.946153,0.964286,0.963889,0.963636,0.956996,0.008508,5
3,0.006596,0.001853,0.017589,0.001356,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.982051,0.982051,1.000000,0.982221,1.000000,0.989265,0.008766,1
4,0.005600,0.000492,0.018785,0.002782,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.892857,0.876841,0.964286,0.925465,0.931890,0.045351,8
5,0.004996,0.001095,0.019390,0.002937,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.982221,0.926743,0.894269,1.000000,0.945682,0.949783,0.037957,6
6,0.006397,0.001199,0.020987,0.004240,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982221,0.839990,0.964572,0.982221,0.963636,0.946528,0.053883,7
7,0.005596,0.001854,0.019788,0.002560,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.947015,0.964286,0.964572,0.982221,0.963912,0.964401,0.011137,2

In [15]:
#here we are predicting the value of teste input with the created module
y_prediction=grid.predict(X_test)

In [16]:
#validation with confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_prediction)
cm

array([[44,  1],
       [ 4, 71]], dtype=int64)

In [17]:
#checking the validation perfomance
from sklearn.metrics import classification_report
cfr=classification_report(Y_test,y_prediction)
print(cfr)

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        45
           1       0.99      0.95      0.97        75

    accuracy                           0.96       120
   macro avg       0.95      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120

In [18]:
from sklearn.metrics import f1_score
f_core= f1_score(Y_test,y_prediction,average='weighted')
f_core
print("bestvalue off1score parameters{}:".format(grid.best_params_),f_core)
print("the confusion matrix:\n",cm)
print("report:\n",cfr)

bestvalue off1score parameters{'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'}: 0.9585802062760588
the confusion matrix:
 [[44  1]
 [ 4 71]]
report:
               precision    recall  f1-score   support

           0       0.92      0.98      0.95        45
           1       0.99      0.95      0.97        75

    accuracy                           0.96       120
   macro avg       0.95      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.9622222222222222