In [1]:
#pandas is a one of the library ,its use to read the database like excel and number related files , 
#it is used for separating the input and output data set
import pandas as pd

In [2]:
#here weare reading the dataset from the inbuild function of pandas
dataset=pd.read_csv("CKD.csv")

In [3]:
# readed dataset
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
# herewe are changing the catagrical input to numerical input 
# new function
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
# this is a new function for reading the input and output names
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
#finding the count of the purchased and unpurchased count or class count
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [7]:
#then here we are separating the input and output with the variables
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[["classification_yes"]]

In [8]:
#sklearn is also one of the library ,we are going to use the libray in every machine learnin project ,its like a default 
#library for ML
#here we are separating the input and output dataset for training and testing prpose ,we are taking 70% for training and 30% for testing testin
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,Y_train)
classifier
y_prediction=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_prediction)
print(cm)
from sklearn.metrics import classification_report
clr=classification_report(Y_test,y_prediction)
print(clr)

[[45  0]
 [ 2 73]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        45
           1       1.00      0.97      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [23]:
from sklearn.metrics import f1_score
f_core= f1_score(Y_test,y_prediction,average='weighted')
f_core

print("the confusion matrix:\n",cm)
print("report:\n",clr)

the confusion matrix:
 [[44  1]
 [22 53]]
report:
               precision    recall  f1-score   support

           0       0.67      0.98      0.79        45
           1       0.98      0.71      0.82        75

    accuracy                           0.81       120
   macro avg       0.82      0.84      0.81       120
weighted avg       0.86      0.81      0.81       120

In [24]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,classifier.predict_proba(X_test)[:,1])

0.9099259259259259

In [10]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()
classifier.fit(X_train,Y_train)
classifier
y_prediction=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_prediction)
print(cm)
from sklearn.metrics import classification_report
clr=classification_report(Y_test,y_prediction)
print(clr)

[[44  1]
 [22 53]]
              precision    recall  f1-score   support

           0       0.67      0.98      0.79        45
           1       0.98      0.71      0.82        75

    accuracy                           0.81       120
   macro avg       0.82      0.84      0.81       120
weighted avg       0.86      0.81      0.81       120

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [21]:
from sklearn.metrics import f1_score
f_core= f1_score(Y_test,y_prediction,average='weighted')
f_core

print("the confusion matrix:\n",cm)
print("report:\n",clr)

the confusion matrix:
 [[44  1]
 [22 53]]
report:
               precision    recall  f1-score   support

           0       0.67      0.98      0.79        45
           1       0.98      0.71      0.82        75

    accuracy                           0.81       120
   macro avg       0.82      0.84      0.81       120
weighted avg       0.86      0.81      0.81       120

In [22]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,classifier.predict_proba(X_test)[:,1])

0.9099259259259259

In [11]:
from sklearn.naive_bayes import BernoulliNB
classifier= BernoulliNB()
classifier.fit(X_train,Y_train)
classifier
y_prediction=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_prediction)
print(cm)
from sklearn.metrics import classification_report
clr=classification_report(Y_test,y_prediction)
print(clr)

[[45  0]
 [ 8 67]]
              precision    recall  f1-score   support

           0       0.85      1.00      0.92        45
           1       1.00      0.89      0.94        75

    accuracy                           0.93       120
   macro avg       0.92      0.95      0.93       120
weighted avg       0.94      0.93      0.93       120

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [19]:
from sklearn.metrics import f1_score
f_core= f1_score(Y_test,y_prediction,average='weighted')
f_core

print("the confusion matrix:\n",cm)
print("report:\n",clr)

the confusion matrix:
 [[44  1]
 [22 53]]
report:
               precision    recall  f1-score   support

           0       0.67      0.98      0.79        45
           1       0.98      0.71      0.82        75

    accuracy                           0.81       120
   macro avg       0.82      0.84      0.81       120
weighted avg       0.86      0.81      0.81       120

In [20]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,classifier.predict_proba(X_test)[:,1])

0.9099259259259259

In [12]:
from sklearn.naive_bayes import ComplementNB
classifier=  ComplementNB()
classifier.fit(X_train,Y_train)
classifier
y_prediction=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_prediction)
print(cm)
from sklearn.metrics import classification_report
clr=classification_report(Y_test,y_prediction)
print(clr)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[[44  1]
 [22 53]]
              precision    recall  f1-score   support

           0       0.67      0.98      0.79        45
           1       0.98      0.71      0.82        75

    accuracy                           0.81       120
   macro avg       0.82      0.84      0.81       120
weighted avg       0.86      0.81      0.81       120

In [18]:
from sklearn.metrics import f1_score
f_core= f1_score(Y_test,y_prediction,average='weighted')
f_core

print("the confusion matrix:\n",cm)
print("report:\n",clr)

the confusion matrix:
 [[44  1]
 [22 53]]
report:
               precision    recall  f1-score   support

           0       0.67      0.98      0.79        45
           1       0.98      0.71      0.82        75

    accuracy                           0.81       120
   macro avg       0.82      0.84      0.81       120
weighted avg       0.86      0.81      0.81       120

In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,classifier.predict_proba(X_test)[:,1])

0.9099259259259259

In [ ]:
from sklearn.naive_bayes import CategoricalNB
classifier=  CategoricalNB()
classifier.fit(X_train,Y_train)
classifier
y_prediction=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_prediction)
print(cm)
from sklearn.metrics import classification_report
clr=classification_report(Y_test,y_prediction)
print(clr)